const MODAL_TYPE_FULL = 'full'
const MODAL_TYPE_CENTER = 'center'
const MODAL_TYPE_LEFT = 'left'
const MODAL_TYPE_RIGHT = 'right'

export const MODAL_TYPES = {
  [MODAL_TYPE_FULL]: MODAL_TYPE_FULL,
  [MODAL_TYPE_CENTER]: MODAL_TYPE_CENTER,
  [MODAL_TYPE_LEFT]: MODAL_TYPE_LEFT,
  [MODAL_TYPE_RIGHT]: MODAL_TYPE_RIGHT,
}
