module.exports = {
  resolve: {
    classnames: require('classnames'),
    'country-telephone-data': require('country-telephone-data'),
    'deep-equal': require('deep-equal'),
    'draft-js': require('draft-js'),
    'draftjs-to-html': require('draftjs-to-html'),
    lodash: require('lodash'),
    'memoize-one': require('memoize-one'),
    moment: require('moment'),
    nanoid: require('nanoid'),
    'object-hash': require('object-hash'),
    'prop-types': require('prop-types'),
    react: require('react'),
    'react-dom': require('react-dom'),
    'react-router': require('react-router'),
    'react-router-dom': require('react-router-dom'),
    'react-tooltip': require('react-tooltip'),
    'sanitize-html': require('sanitize-html'),
  },
}
